---

- debug: msg="##### R Analytics Server Deployment {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

# Running the 5GTANGO R Analytics Server (Docker container)

- name: R Analytics Server - running Docker containers
  docker_container:
    name: analyticserver
    image: "{{ repository }}/analyticserver:{{ version }}"
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - analyticserver
    published_ports: "8083:80"
    restart_policy: "always"
