---
# Deploying VnV Databases

# Deploying VnV Components

# deploy mongo
- import_tasks: mongo.yml

# deploy tng-vnv-lcm
- import_tasks: lcm.yml

# deploy tng-vnv-tee
- import_tasks: tee.yml

# deploy tng-cat
- import_tasks: cat.yml

# deploy tng-rep
- import_tasks: rep.yml

# deploy tng-gtk-common
- import_tasks: gtk-common.yml

# deploy tng-gtk-gtw
- import_tasks: api-gtw.yml

# deploy tng-sdk-pkg.yml
- import_tasks: tng-sdk-pkg.yml