---

- debug: msg="##### VnV Planner Deployment {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

# Running the 5GTANGO VnV Planner (Docker container)

- name: VnV Planner - running Docker containers
  docker_container:
    name: tng-vnv-planner
    image: "{{ repository }}/tng-vnv-planner:{{ version }}"
    env:
      APP_GK_BASE_URL: "{{ app_gk_base_url }}"
      APP_CAT_BASE_URL: "{{ catalogue_url }}"
      LOGGING_LEVEL_ORG_APACHE_HTTP_WIRE: "{{ app_vnv_logging_level }}"
      LOGGING_LEVEL_SUN_NET_WWW_PROTOCOL_HTTP: "{{ app_vnv_logging_level }}"
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-vnv-planner
    published_ports: "6100:6100"
    restart_policy: "always"
