---

- debug: msg="##### VnV Curator Deployment {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

# Running the 5GTANGO VnV Curator (Docker container)

- name: VnV Curator - running Docker containers
  docker_container:
    name: tng-vnv-curator
    image: "{{ repository }}/tng-vnv-curator:{{ version }}"
    env:
      APP_GK_BASE_URL: "{{ app_gk_base_url }}"
      APP_CAT_BASE_URL: "{{ catalogue_url }}"
      LOGGING_LEVEL_ORG_APACHE_HTTP_WIRE: "{{ app_vnv_logging_level }}"
      LOGGING_LEVEL_SUN_NET_WWW_PROTOCOL_HTTP: "{{ app_vnv_logging_level }}"
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-vnv-curator
    published_ports: "6200:6200"
    restart_policy: "always"
