---

- debug: msg="##### VnV Curator Deployment {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

# Running the 5GTANGO VnV Curator (Docker container)

- name: VnV Curator - running Docker containers
  docker_container:
    name: tng-vnv-curator
    image: "{{ repository }}/tng-vnv-curator:{{ version }}"
    env:
      CAT_BASE: "http://tng-cat:4011"
      PLATFORM_ADAPTER_BASE: "http://tng-vnv-platform-adapter:5001"
      PLANNER_BASE: "http://tng-vnv-planner:6100"
      EXECUTOR_BASE: "http://tng-vnv-executor:8080"
      LB_ALGO: "round_robin"
      DOCKER_HOST: "unix://var/run/docker.sock"

    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-vnv-curator
    published_ports: "6200:6200"
    restart_policy: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
