---
# Running the SONATA INFLUXDB (Docker container)

- debug: msg="##### SP INFLUXDB DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"

- name: MONIT InfluxDB - running on Docker containers
  docker_container:
    name: son-monitor-influxdb
    image: "{{ repository }}/son-monitor-influxdb:{{ tng_ver }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: always
    network_mode: bridge
    networks:
    - name: "{{ docker_netw_name }}"
      aliases:
        - son-monitor-influxdb
        - influxdb
        - influx
    published_ports: 8086:8086

- name: Wait until the InfluxDB is UP
  wait_for: host=0.0.0.0 port=8086 timeout=30 delay=10 state=started

