---

- name: MANO Placement Executive Plugin (Docker container)
  docker_container:
    name: placementexecutive
    image: "{{ repository }}/placementexecutive:{{ version }}"
    env:
      broker_host: amqp://guest:guest@son-broker:5672/%2F
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - placementexecutive
    state: started
    pull: true
