---
# Running the 5GTANGO SLA Manager Framework
- debug: msg="##### 5GTANGO SLA Manager Framework DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
- name: 5GTANGO SLA Manager Framework - running Docker containers
  docker_container:
    name: tng-sla-mgmt
    image: "{{ repository }}/tng-sla-mgmt:{{ version }}"
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-sla-mgmt
    restart_policy: "always"
    published_ports:
      - "8080:8080"

