---

# talk to all hosts just so we can learn about them
- hosts: "{{ target }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Create a docker network
      docker_network:
        name: "{{ docker_netw_name }}"
        state: present
