---

- include_vars: "{{ lookup('env','PWD') }}/inventory/group_vars/all"

- name: create Docker group
  group:
    name: docker
    state: present

- name: add Docker group to TNG user
  user:
    name: "{{ tng_user }}"
    shell: /bin/bash
    groups: docker
    append: yes

- name: create a directory for Docker logging
  file:
    path: /var/log/docker
    state: directory
    owner: tango
    group: docker
    mode: 0775
  become: true

- include_tasks: "{{ lookup('env','PWD') }}/roles/docker/tasks/{{ ansible_distribution_release }}.yml"

- include_tasks: "{{ lookup('env','PWD') }}/roles/docker/tasks/networks.yml"

- name: restart docker on Systemd (Ubuntu 16 and CentOS 7)
  systemd: name=docker state=reloaded daemon_reload=yes

