- name: Docker User Defined Network
  shell: docker network list
  become: true
  ignore_errors: true
  no_log: true
  register: dockernet

- debug:
    var: dockernet

- name: stop all the running Docker containers 
  shell: "docker stop $(docker ps -a -q)"
  become: true
  when: "'tng_docker_net' in dockernet"

- name: remove Docker network
  shell: "docker network rm tng_docker_net"
  become: true
  when: "'tng_docker_net' in dockernet"

- name: Docker creating network
  shell: 'docker network create --driver=bridge --subnet={{ docker_addr_space }} --gateway={{ docker_gateway }} --ip-range={{ docker_ip_range }} "tng_docker_net"'
  notify:
    - restart docker
  become: true

